core/api/urls.py
from cabinet.api import (
    DriverRegisterAPI,
    GetAllSettingsAPIView,
    GetOrCreateUserFromTelegramAPI,
    GetUserExtendedAPI,
    GetUserFromTelegramAPI,
    OutOnTheLineDriver,
    RegisterUserFromTelegramAPI,
    UpdateUserAPIView,
    finish_driver_work_day,
    update_user_balance_api_view,
    update_users_location, GetUserApiByTelegramTokenAuth,
)
from dispatcher.api import (
    CreateOrderAPI,
    DriverAnalyticsOrderAPIView,
    DriverPickOrderAPI,
    ReCreateOrderAPI,
    UpdateOrderAPI,
    UpdateOrderStatusAPI,
    create_order_revision_api_view,
    get_active_order_api_view,
    get_active_ride_api_view,
    get_price_api_view,
    set_order_review,
    GetMapCenterAPIView, GetActiveOrderByTelegramAuthToken,
    GetRaitings
)
from django.urls import path
from referral.api import get_present_from_order, pick_coupon_from_telegram

urlpatterns = [
    path("users/registerFromTelegram/", RegisterUserFromTelegramAPI.as_view()),
    path("users/registerDriver/", DriverRegisterAPI.as_view()),

    path(
        "users/getOrCreateUserFromTelegram/", GetOrCreateUserFromTelegramAPI.as_view()
    ),
    path("users/getUserFromTelegram/", GetUserFromTelegramAPI.as_view()),
    path("users/GetUserApiByTelegramTokenAuth/<str:token>/", GetUserApiByTelegramTokenAuth.as_view()),
    path("users/getUserExtended/", GetUserExtendedAPI.as_view()),
    path("users/updateUserLocations/", update_users_location),
    path("users/updateUserBalance/", update_user_balance_api_view),
    path("users/outOnTheLineDriver/", OutOnTheLineDriver.as_view()),
    path("users/finishWorkDay/", finish_driver_work_day),
    path("users/updateUser/<int:pk>/", UpdateUserAPIView.as_view()),
    path("users/getRaitings/<int:pk>/", GetRaitings.as_view()),

    path("orders/createOrder/", CreateOrderAPI.as_view()),
    path("orders/reCreateOrder/", ReCreateOrderAPI.as_view()),
    path("orders/updateOrder/<int:pk>", UpdateOrderAPI.as_view()),
    path("orders/driverPickOrder/", DriverPickOrderAPI.as_view()),
    path("orders/updateOrderStatus/<int:order_id>/", UpdateOrderStatusAPI.as_view()),
    path("orders/getClientActiveOrder/", get_active_order_api_view),
    path("orders/getDriverActiveRide/", get_active_ride_api_view),
    path("orders/setReview/", set_order_review),
    path("orders/createOrderRevision/", create_order_revision_api_view),
    path("orders/getPrice/", get_price_api_view),
    path("orders/getActiveByTelegramAuthToken/<str:token>/", GetActiveOrderByTelegramAuthToken.as_view()),

    path("coupons/pickCouponFromTelegram/", pick_coupon_from_telegram),
    path("presents/getPresentFromOrder/", get_present_from_order),

    path("getAllSettings/", GetAllSettingsAPIView.as_view()),
    path("map-center/", GetMapCenterAPIView.as_view()),

    path('analytics/driver/order/<int:pk>', DriverAnalyticsOrderAPIView.as_view()),
]

core/cabinet/urls.py
from django.urls import path

from . import views
from .views import (
    LoginView,
    admin_settings_view,
    city_create_view,
    city_detail_view,
    city_list_view,
    coupon_create_view,
    coupon_detail_view,
    coupon_list_view,
    dashboard_view,
    index_view,
    logout_view,
    message_list_view,
    order_detail_driver_view,
    orders_list_admin_view,
    orders_view,
    user_detail_view,
    users_list_view,
    telegram_auth_token_login,
    coupon_list_driver_view,
    apply_coupon_view,
)


from referral import views as referral_views

app_name = "cabinet"


urlpatterns = [
    # Driver
    path("", index_view, name="index"),
    path("orders/", orders_view, name="orders"),
    path("orders/<int:pk>/", order_detail_driver_view, name="order"),
    path("coupons/", coupon_list_driver_view, name="coupon_list_driver"),
    path("coupons/apply_coupon/<int:pk>", apply_coupon_view, name="apply_coupon"),
    path("admin/orders/", orders_list_admin_view, name="order_list_admin"),
    path("admin/users/", users_list_view, name="users"),
    path("admin/users/<int:pk>/", user_detail_view, name="user"),
    path("admin/coupons/", coupon_list_view, name="coupon_list_admin"),
    path("admin/coupons/<int:pk>/", coupon_detail_view, name="coupon_detail"),
    path("admin/coupons/create/", coupon_create_view, name="coupon_create"),
    path("admin/cities/", city_list_view, name="city_list"),
    path("admin/cities/<int:pk>/", city_detail_view, name="city_detail"),
    path("admin/cities/create/", city_create_view, name="city_create"),
    path("admin/messages/", message_list_view, name="message_list"),
    path("admin/messages/create/", views.message_create_view, name="message_create"),
    path("admin/messages/<int:pk>/", views.message_detail_view, name="message_detail"),
    path("admin/mailings/", views.mailing_list_view, name="mailing_list"),
    path("admin/mailings/create/", views.mailing_create_view, name="mailing_create"),
    path("admin/mailings/<int:pk>/", views.mailing_detail_view, name="mailing_detail"),
    path("admin/raffles/", views.raffle_list_view, name="raffle_list"),
    path("admin/raffles/create/", views.raffle_create_view, name="raffle_create"),
    path("admin/raffles/<int:pk>/", views.raffle_detail_view, name="raffle_detail"),
    path("admin/presents/", referral_views.present_list_view, name="present_list_view"),
    path(
        "admin/presents/create/",
        referral_views.present_create_view,
        name="present_create_view",
    ),
    path(
        "admin/presents/<int:pk>/",
        referral_views.present_detail_view,
        name="present_detail_view",
    ),
    # Admin
    path("admin/dashboard/", dashboard_view, name="dashboard"),
    path("admin/settings/", admin_settings_view, name="settings_admin"),
    path("login/", LoginView.as_view(), name="login"),
    path(
        "telegram_auth_token_login/<str:token>/",
        telegram_auth_token_login,
        name="telegram_auth_token_login",
    ),
    path("logout/", logout_view, name="logout"),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpRequest, HttpResponse
from django.urls import include, path, reverse
from django.views.generic import RedirectView




def error_403_view(request: HttpRequest, exception=None):
    return HttpResponse(
        '<h1>Доступ запрещён</h1><br><a href="%s">Вход</a>' % reverse("cabinet:login")
    )


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("cabinet/", include("cabinet.urls", namespace="cabinet")),
]

if settings.LANDING_ENABLED:
    urlpatterns.append(path("", include("landing.urls", namespace="landing")))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler403 = error_403_view

core/templates/cabinet/forms/city/city_create.html
{% extends 'cabinet/layout/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="container-fluid">
	    <div class="page-title">
	      <div class="row">
	        <div class="col-6">
	          <h3>Регистрация города</h3>
	        </div>
	        <div class="col-6">
	          <ol class="breadcrumb">
	            <li class="breadcrumb-item"><a href="/cabinet"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg></a></li>
	            <li class="breadcrumb-item">Меню администратора</li>
	            <li class="breadcrumb-item active">Регистрация города</li>
	          </ol>
	        </div>
	      </div>
	    </div>
	  </div>
    <div class="container-fluid">
		<div class="row size-column mb-5">
            <div class="col-xl-12 box-col-12 col-md-12">
                {% crispy form %}
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/cabinet/forms/city/city_detail.html
{% extends 'cabinet/layout/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="container-fluid">
	    <div class="page-title">
	      <div class="row">
	        <div class="col-6">
	          <h3>Информация о городе #{{ city.pk }}</h3>
	        </div>
	        <div class="col-6">
	          <ol class="breadcrumb">
	            <li class="breadcrumb-item"><a href="/cabinet"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg></a></li>
	            <li class="breadcrumb-item">Меню администратора</li>
	            <li class="breadcrumb-item active">Информация о городе</li>
	          </ol>
	        </div>
	      </div>
	    </div>
	  </div>
    <div class="container-fluid">
		<div class="row size-column mb-5">
            <div class="col-xl-12 box-col-12 col-md-12">
                {% crispy city_form %}
            </div>
            <div class="col-xl-6 box-col-12 col-md-12">
                {% crispy cost_per_km_form %}
            </div>
            <div class="col-xl-6 box-col-12 col-md-12">
                {% crispy cost_per_baby_chair_form %}
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/cabinet/forms/city/city_list.html
{% extends 'cabinet/layout/base.html' %}
{% load django_tables2 %}

{% block title %}
    <title>ТаксиБер — Список городов</title>

{% endblock title %}


{% block content %}
     <div class="container-fluid">
            <div class="page-title">
              <div class="row">
                <div class="col-6">
                  <h3>Список городов</h3>
                </div>
                <div class="col-6">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url_dashboard }}"><i data-feather="home"></i></a></li>
                    <li class="breadcrumb-item">Меню администратора</li>
                    <li class="breadcrumb-item active">Список городов</li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
    <div class="col-12 mb-5">
        <a href="{% url 'cabinet:city_create' %}" class="btn btn-pill btn-primary">Зарегистрировать город</a>
    </div>
    <div class="col-12">
        {% render_table table %}
    </div>

{% endblock content %}